version: '3.4'

services:
  mongo:
    image: mongo

  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: ESourcing.Products/Dockerfile

  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
       context: .
       dockerfile: ESourcing.Sourcing/Dockerfile
