version: '3.4'

services:
  mongo:
     image: mongo

  rabbitmq:
     image: rabbitmq:3-management

  sql:
     image: mcr.microsoft.com/mssql/server

  redis:
     image: redis

  nginx:
     image: nginx

  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: ESourcing.Products/Dockerfile

  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
       context: .
       dockerfile: ESourcing.Sourcing/Dockerfile

  esourcing.orders:
    image: ${DOCKER_REGISTRY-}esourcingorders
    build:
      context: .
      dockerfile: ESourcing.Order/Dockerfile


  esourcing.apigateway:
    image: ${DOCKER_REGISTRY-}esourcingapigateway
    build:
      context: .
      dockerfile: ESourcing.ApiGateway/Dockerfile

